FROM mcr.microsoft.com/devcontainers/javascript-node

RUN apt-get update && apt-get install -y \
    git \
    curl \
    build-essential \
    gcc \
    g++ \
    make \
    python3 \
    python3-pip \
    shellcheck \
    clang \
    clang-format \
    git-secrets